# Generated by Django 4.2.11 on 2024-05-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todoitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
    ]
