# Generated by Django 4.2.11 on 2024-05-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_remove_todoitem_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
